blog/urls.py
from django.conf.urls import patterns, url

from .views import (PostView, BlogView, BlogListView, LoginView, LogoutView,
                    UserFeedView, SubscribeView, UnSubscribeView, MarkReadView, MarkUnreadView,
                    AddPostView)


urlpatterns = patterns('',
    url(r'^$', BlogListView.as_view(), name='index'),
    url(r'^post/(?P<pk>\d+)/$', PostView.as_view(), name='post_view'),
    url(r'^blog/(?P<pk>\d+)/$', BlogView.as_view(), name='blog_view'),
    url(r'^blog_list/$', BlogListView.as_view(), name='blog_list'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^user_feed/$', UserFeedView.as_view(), name='user_feed'),
    url(r'^subscribe/$', SubscribeView.as_view(), name='subscribe'),
    url(r'^unsubscribe/$', UnSubscribeView.as_view(), name='unsubscribe'),
    url(r'^mark_read/$', MarkReadView.as_view(), name='mark_read'),
    url(r'^mark_unread/$', MarkUnreadView.as_view(), name='mark_unread'),
    url(r'^add_post/$', AddPostView.as_view(), name='add_post'),
)

devblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_delete, post_save

from .utils import send_message


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    subscribed_blogs = models.CommaSeparatedIntegerField(u'Подписан на блоги',
        blank=True, max_length=1024)
    readed_posts = models.CommaSeparatedIntegerField(u'Прочитанные сообщения',
        blank=True, max_length=1024)

    class Meta:
        verbose_name = u'профиль'
        verbose_name_plural = u'профили'

    def __unicode__(self):
        return self.user.username


class Blog(models.Model):
    user = models.OneToOneField(User, verbose_name=u'Автор',
        related_name='blog')

    class Meta:
        verbose_name = u'блог'
        verbose_name_plural = u'блоги'

    def __unicode__(self):
        return u'Блог {}'.format(self.user.username)

    def post_count(self):
        return self.posts.count()


class Post(models.Model):
    blog = models.ForeignKey(Blog, related_name='posts', verbose_name=u'Блог')
    title = models.CharField(u'Заголовок', max_length=255)
    text = models.TextField(u'Текст')
    date = models.DateTimeField(u'Дата', auto_now_add=True)

    class Meta:
        verbose_name = u'запись'
        verbose_name_plural = u'записи'
        ordering = ['-date']

    def __unicode__(self):
        return u'Запись {}'.format(self.title)

    def get_absolute_url(self):
        return u'{}{}'.format(
            Site.objects.get_current(),
            reverse('post_view', args=[str(self.pk)])
        )


def create_user(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        Blog.objects.create(user=instance)
post_save.connect(create_user, sender=User)

post_save.connect(send_message, sender=Post)

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Post

class AddPostForm(forms.ModelForm):
    class Meta(object):
        model = Post
        exclude = ('date',)

blog/views.py
# -*- coding: utf-8 -*-
import logging

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import (REDIRECT_FIELD_NAME, login as auth_login,
    logout as auth_logout)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import (ListView, DetailView, FormView, RedirectView,
    TemplateView, CreateView)

from .forms import AddPostForm
from .models import Post, Blog

log = logging.getLogger(__name__)

class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class LoginView(FormView):

    success_url = '/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'registration/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.REQUEST.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class PostListView(ListView):
    template_name = 'index.html'
    context_object_name = 'post_list'
    model = Post


class PostView(DetailView, LoginRequiredMixin):
    model = Post
    template_name = 'post.html'

    def get_context_data(self, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        context['can_mark'] = True
        readed_posts = self.request.user.profile.readed_posts
        if readed_posts:
            if str(self.object.pk) in readed_posts.split(','):
                context['can_mark'] = False
        return context


class BlogView(DetailView):
    template_name = 'blog.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        context['can_subscribe'] = False
        if self.request.user.is_authenticated:
            if self.object.user != self.request.user: #нельзя подписаться на свой блог
                subscribed_blogs = self.request.user.profile.subscribed_blogs
                if subscribed_blogs:
                    context['is_subscribed'] = str(self.object.pk) in subscribed_blogs.split(',')
                    context['can_subscribe'] = True
        return context


class BlogListView(ListView):
    template_name = 'blog_list.html'
    context_object_name = 'blog_list'
    model = Blog


class UserFeedView(TemplateView, LoginRequiredMixin):
    template_name = 'user_feed.html'

    def get_context_data(self, **kwargs):
        if self.request.user.profile.subscribed_blogs:
            user_blogs = self.request.user.profile.subscribed_blogs.split(',')
            kwargs['post_list'] = Post.objects.filter(blog__in=user_blogs)
        return kwargs


class SubscribeView(RedirectView):
    def get(self, request, *args, **kwargs):
        blog_id = request.GET.get('blog_id')
        get_object_or_404(Blog, pk=blog_id)
        if request.user.profile.subscribed_blogs:
            user_blogs = request.user.profile.subscribed_blogs.split(',')
            if blog_id not in user_blogs:
                user_blogs.append(blog_id)
                request.user.profile.subscribed_blogs = u','.join(user_blogs)
        else:
            request.user.profile.subscribed_blogs = u','.join([blog_id])
        request.user.profile.save()
        return redirect(request.META['HTTP_REFERER'])


class UnSubscribeView(RedirectView):
    def get(self, request, *args, **kwargs):
        blog_id = request.GET.get('blog_id')
        blog = get_object_or_404(Blog, pk=blog_id)
        user_blogs = request.user.profile.subscribed_blogs.split(',')
        if blog_id in user_blogs:
            user_blogs.remove(blog_id)
            request.user.profile.subscribed_blogs = ','.join(user_blogs)

            readed_posts = request.user.profile.readed_posts.split(',')
            for post in blog.posts.all():
                if str(post.pk) in readed_posts:
                    readed_posts.remove(str(post.pk))
            request.user.profile.readed_posts = readed_posts
            request.user.profile.save()
        return redirect(request.META['HTTP_REFERER'])


class MarkReadView(RedirectView):
    def get(self, request, *args, **kwargs):
        post_id = request.GET.get('post_id')
        get_object_or_404(Post, pk=post_id)
        if request.user.profile.readed_posts:
            readed_posts = request.user.profile.readed_posts.split(',')
            if post_id not in readed_posts:
                readed_posts.append(post_id)
                request.user.profile.readed_posts = u','.join(readed_posts)
        else:
            request.user.profile.readed_posts = u','.join([post_id])
        request.user.profile.save()
        return redirect(request.META['HTTP_REFERER'])


class MarkUnreadView(RedirectView):
    def get(self, request, *args, **kwargs):
        post_id = request.GET.get('post_id')
        get_object_or_404(Post, pk=post_id)
        if request.user.profile.readed_posts:
            readed_posts = request.user.profile.readed_posts.split(',')
            if post_id in readed_posts:
                readed_posts.remove(post_id)
                request.user.profile.readed_posts = u','.join(readed_posts)
                request.user.profile.save()
        return redirect(request.META['HTTP_REFERER'])


class AddPostView(CreateView):
    form_class = AddPostForm
    template_name = 'add_post.html'
    success_url = '/'

blog/templates/add_post.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
    <form method="post" action="">{% csrf_token %}
        <input type="hidden" name="blog" id="id_blog" value="{{ request.user.blog.pk }}">
        <div class="form-group">
            <label for="id_title">Заголовок</label>
            <input type="text" class="form-control" id="id_title" name="title" placeholder="Заголовок">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Текст</label>
            <textarea class="form-control" rows="4" id="id_text" name="text" placeholder="Текст"></textarea>
        </div>
        <button type="submit" class="btn btn-default">Добавить</button>
    </form>
    </div>
{% endblock content %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-eqiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Devhub blogs</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'assets/js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'assets/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Devhub blogs</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'blog_list' %}">Блоги</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'user_feed' %}">Моя лента</a></li>
                <li><a href="{% url 'add_post' %}">Добавить запись в блог</a></li>
                {% endif %}
          </ul>
        {% if not request.user.is_authenticated %}
          <form class="navbar-form navbar-right" method="post" action="{% url 'login' %}">{% csrf_token %}
            <div class="form-group">
              <input type="text" placeholder="Name" name="username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Войти</button>
          </form>
          {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'logout' %}">Выйти({{ request.user.username }})</a></li>
          </ul>
          {% endif %}
        </div><!--/.navbar-collapse -->

      </div>
    </nav>

    <div class="container">

    {% block content %}
    {% endblock content %}

    </div><!-- /.container -->

    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

blog/templates/blog.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <h4 class="pull-left">Блог {{ object.user }}</h4>
        {% if request.user.is_authenticated %}
            {% if can_subscribe %}
                {% if is_subscribed %}
                   <h4 class="pull-right"><a href="{% url 'unsubscribe' %}?blog_id={{ object.pk }}">Отписаться от блога</a></h4>
                {% else %}
                    <h4 class="pull-right"><a href="{% url 'subscribe' %}?blog_id={{ object.pk }}">Подписаться на блог</a></h4>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
    <div class="row">
    {% for post in object.posts.all %}
        <div class="col-md-3">
            <h6 class="pull-right">{{ post.date|date:"d.m.Y"  }}</h6>
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|truncatechars:20 }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

blog/templates/blog_list.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
    {% for blog in blog_list %}
        <div class="col-md-4">
            {% if blog.pk in request.user.profile %}
            {% endif %}
            <h4>Пользователь {{ blog.user.username }}</h4>
            <p>Записей: {{ blog.post_count }}</p>
            <p><a class="btn btn-default" href="{% url 'blog_view' blog.id %}" role="button">Перейти &raquo;</a></p>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
    {% for post in post_list %}
        <div class="col-md-4">
            <h6 class="pull-left">{{ post.blog.user.username }}</h6>
            <h6 class="pull-right">{{ post.date|date:"d.m.Y"  }}</h6>
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|truncatechars:20 }}</p>
            <p><a class="btn btn-default" href="{% url 'post_view' post.id %}" role="button">Больше &raquo;</a></p>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

blog/templates/post.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <h6 class="pull-right">{{ post.date|date:"d.m.Y H:s"  }}</h6>
        <h4><a href="{% url 'blog_view' post.blog.pk %}">Блог {{ post.blog.user }}</a></h4>
        {% if can_mark %}
            <h4><a href="{% url 'mark_read' %}?post_id={{ post.pk }}">Пометить прочитанным</a></h4>
        {% else %}
            <h4><a href="{% url 'mark_unread' %}?post_id={{ post.pk }}">Снять отметку прочтения</a></h4>
        {% endif %}

        <h2>{{ post.title }}</h2>
        <p>{{ post.text}}</p>
    </div>
{% endblock content %}

blog/templates/user_feed.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
    {% for post in post_list %}
        <div class="col-md-4">
            <h6 class="pull-left">{{ post.blog.user.username }}</h6>
            <h6 class="pull-right">{{ post.date|date:"d.m.Y"  }}</h6>
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|truncatechars:20 }}</p>
            <p><a class="btn btn-default" href="{% url 'post_view' post.id %}" role="button">Больше &raquo;</a></p>
        </div>
    {% empty %}
        <p>В вашей ленте нет записей</p>
    {% endfor %}
    </div>
{% endblock content %}